server:
  port:

spring:
  profiles:
    default: dev

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate.ddl-auto:
    show-sql:
    properties:
      hibernate.format_sql:
      hibernate.default_batch_fetch_size:
    open-in-view: false
    defer-datasource-initialization:

  sql.init.mode:

### debugging log disable ###
debug:

### actuator enable ###
management.endpoints.web.exposure.include:

logging:
  level:
    site.packit.packit:
    org.springframework.web.servlet:
    org.hibernate.type.descriptor.sql.BasicBinder:

### Custom App Setting ###
app:
  ### JWT ###
  jwt:
    secret:
      access-token-secret-key:
      refresh-token-secret-key:
    expiry:
      access-token-expiry:
      refresh-token-expiry:

  ### Cookie ###
  cookie:
    oauth2-authorization-request-cookie-name:
    redirect-uri-param-cookie-name:
    refresh-token-cookie-name:
    cookie-expire-seconds: